---
- name: Ensure iptables is present.
  ansible.builtin.package:
    name: iptables
    state: present

- name: Flush iptables the first time playbook runs.
  ansible.builtin.command: >
    iptables -F
    creates=/etc/firewall.bash

- name: Copy firewall script into place.
  ansible.builtin.template:
    src: firewall.bash.j2
    dest: /etc/firewall.bash
    owner: root
    group: root
    mode: 0744
  notify: Restart firewall

- name: Copy firewall init script into place.
  ansible.builtin.template:
    src: firewall.init.j2
    dest: /etc/init.d/firewall
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr != 'systemd'"

- name: Copy firewall systemd unit file into place (for systemd systems).
  ansible.builtin.template:
    src: firewall.unit.j2
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"

- name: Configure the firewall service.
  ansible.builtin.service:
    name: firewall
    state: "{{ iptables_state }}"
    enabled: "{{ iptables_enabled_at_boot }}"

- name: Disable other firewalls if necessary
  ansible.builtin.import_tasks: disable-other-firewalls.yml
  when: iptables_disable_firewalld or iptables_disable_ufw
