---
# This will hold the build and we can `molecule login` to the docker image
- name: Converge
  hosts: all
  become: true

  vars:
    # Added to prevent test failures in CI.
    iptables_enable_ipv6: false

    # Added for a test.
    iptables_allowed_tcp_ports:
      - "9123"

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 1200
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: shaneholloman.iptables
